### PR TITLE
UI/setup icons

### PR DESCRIPTION
**Pull request by sub1120**
Icon setup is complete,

## How to use?
1. Import Icon component
```javascript
import Icon from "@/components/icon/Icon";
```

2. Next we just need to use `<Icon/>` component 
```javascript
<Icon id="icon-id"/>
```
where `icon-id`, can be from any of one valid types suggested by the editor.

image

Additionally, we can alter icon size, fill color, and stroke color, using tailwind classes
```javascript
<Icon id="MapPin" className="h-12 w-12 hover:stroke-primary"></Icon>
```
## How to add a new Icon
1. Add new `<symbol>`.
```javascript
// /public/sprite.svg
<symbol id="icon-id" viewBox="0 0 24 24">
     // Your icon paths
</symbol>
```
**Note:** Remove following attributes from your paths, if present fillColor="anyValue" stroke="currentColor", for better control over style overrding.

2. Add your `icon-id` to `idType`

```javascript
// types/icon/index.ts
export type idType = "icon-id" | .....
```
This step is to enhance code suggestions, while using Icons.

More Examples
```javascript
// plain icons with default fill, stroke, and size.
 <Icon id="XCircle"></Icon>
 <Icon id="XCircle"></Icon>
 <Icon id="XCircle"></Icon>
 <Icon id="XCircle"></Icon>
 <Icon id="XCircle"></Icon>
 <Icon id="XCircle"></Icon>

// change default stroke color
<Icon id="Pen" className="stroke-primary"></Icon>
<Icon id="Pen" className="stroke-primary"></Icon>
<Icon id="Pen" className="stroke-primary"></Icon>
<Icon id="Pen" className="stroke-primary"></Icon>
<Icon id="Pen" className="stroke-primary"></Icon>
<Icon id="Pen" className="stroke-primary"></Icon>

// fill color with no stroke
<Icon id="ThumbsUp" className="fill-primary stroke-none"></Icon>
<Icon id="ThumbsUp" className="fill-primary stroke-none"></Icon>
<Icon id="ThumbsUp" className="fill-primary stroke-none"></Icon>
<Icon id="ThumbsUp" className="fill-primary stroke-none"></Icon>
<Icon id="ThumbsUp" className="fill-primary stroke-none"></Icon>
<Icon id="ThumbsUp" className="fill-primary stroke-none"></Icon>

// stroke color success
<Icon id="CheckSquare" className="stroke-success-600  "></Icon>
<Icon id="CheckSquare" className="stroke-success-600  "></Icon>
<Icon id="CheckSquare" className="stroke-success-600  "></Icon>
<Icon id="CheckSquare" className="stroke-success-600  "></Icon>
<Icon id="CheckSquare" className="stroke-success-600  "></Icon>
<Icon id="CheckSquare" className="stroke-success-600  "></Icon>

// stroke color warning
<Icon id="Prohibit" className="stroke-warning-600"></Icon>
<Icon id="Prohibit" className="stroke-warning-600"></Icon>
<Icon id="Prohibit" className="stroke-warning-600"></Icon>
<Icon id="Prohibit" className="stroke-warning-600"></Icon>
<Icon id="Prohibit" className="stroke-warning-600"></Icon>
<Icon id="Prohibit" className="stroke-warning-600"></Icon>

// size variation + hover effect
<Icon id="MapPin" className="hover:stroke-primary"></Icon>
<Icon id="MapPin" className="h-12 w-12 hover:stroke-primary"></Icon>
<Icon id="MapPin" className="h-14 w-14 hover:stroke-primary"></Icon>
<Icon id="MapPin" className="h-16 w-16 hover:stroke-primary"></Icon>
<Icon id="MapPin" className="h-20 w-20 hover:stroke-primary"></Icon>
<Icon id="MapPin" className="h-24 w-24 hover:stroke-primary"></Icon>
```
Output
image

### CODE REVIEW

**Review by shivamvijaywargi — APPROVED** [review]
All good, but may I know the reason to remove the react icons dependency?

**Comment by shivamvijaywargi** [comment]
Also, can you please guide how can we add a new icon in the future(if required)?

**Comment by sub1120** [comment]
> All good, but may I know the reason to remove the react icons dependency?

Reason being,
 - as of now we have not used any react-icon in project, so I though we can add it later, when required. 
 - And better, we can try to make a single method to manage all icons, until we get stuck somewhere with current method.

**Comment by sub1120** [comment]
> Also, can you please guide how can we add a new icon in the future(if required)?

Sure, I will add it here and in discussion also.

**Pull request merged**
